name: Packaging

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  wheels:
    name: Build ${{ matrix.os }} wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    env:
      CIBW_SKIP: cp27-* pp*
      CIBW_BEFORE_ALL: |
        # Common setup commands for both OS
        pip install cmake>=3.5 &&
        git clone https://github.com/libjxl/libjxl.git --recursive --shallow-submodules &&
        cd libjxl* &&
        git checkout v0.10.1 &&
        mkdir build && cd build &&
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_DEVTOOLS=OFF .. &&
        cmake --build . --config Release &&
        cmake --install . --config Release &&

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.3.0
      with:
        python-version: |
            3.12
            3.13

    - name: Install vcpkg and Brotli
      run: |
        # Install vcpkg
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        # Install Brotli using vcpkg
        ./vcpkg install brotli

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_ARCHS: auto AMD64 ARM64 x86

    - uses: actions/upload-artifact@master
      with:
        name: wheelhouse-${{ matrix.os }}
        path: wheelhouse

    - name: Publish package
      run: python -m pip install twine && python -m twine upload wheelhouse/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}

  sdist:
    name: Build source distribution
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: |
            3.12
            3.13

    - name: Install dependencies
      run: |
        pip install cmake>=3.5 &&
        git clone https://github.com/libjxl/libjxl.git --recursive --shallow-submodules &&
        cd libjxl* &&
        git checkout v0.10.1 &&
        mkdir build && cd build &&
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_DEVTOOLS=OFF .. &&
        cmake --build . --config Release &&
        cmake --install . --config Release

    - name: Install python-build
      run: python -m pip install build

    - name: Create packages
      run: python -m build --sdist .

    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
